#!/usr/bin/env python3
"""puush for linux

Usage:
    puush [-cmd] upload <file>...
    puush [-cmd] (window | desktop | area)
    puush -h | --help

Commands:
    upload          Upload the specified file(s)
    window          Take a screenshot of the current window and upload it
    desktop         Take a screenshot of the entire desktop and upload it
    area            Take a screenshot of a certain area and upload it

Options:
    -c --clipboard  Copy the URL to clipboard additionally to STDOUT
    -m --mute       Mute. Don't play beep.
    -d --debug      Show debug messages.
    -h --help       Show this help
"""

import os
import re
import sys
import subprocess as sp

import requests
import docopt


APIURL = "https://puush.me/api/up"
VERSION = "1.0"


def upload_file(path, api_key):
    payload = {
        "k": api_key,
        "z": "something"
    }
    files = {
        "f": open(path, "rb")
    }

    r = requests.post(APIURL, data=payload, files=files)
    url = re.search("(?P<url>https?://[^\s,]+)", r.text).group("url")
    return url


def copy_to_clipboard(content):
    with open("/tmp/puushclip", "w") as f:
        f.write(content)
    sp.check_call(["xclip", "-selection", "clipboard", "-i", "/tmp/puushclip"])
    os.remove("/tmp/puushclip")


def main(args):
    if "PUUSH_API_KEY" in os.environ:
        api_key = os.environ["PUUSH_API_KEY"]
    else:
        try:
            with open(os.path.expanduser("~/.config/puush/key"), "r") as f:
                api_key = f.read().strip()
        except:
            if args["--debug"]:
                raise
            print("Failed to get api key. Please follow the instructions at https://github.com/KoffeinFlummi/puush-linux .", file=sys.stderr)
            return 1

    files = args["<file>"]

    scrot_options = None
    if args["window"]:
        scrot_options = ["-b", "-u"]
    if args["desktop"]:
        scrot_options = []
    if args["area"]:
        scrot_options = ["-s"]

    if scrot_options is not None:
        try:
            sp.check_call(["scrot"] + scrot_options + ["/tmp/puushscrot.png"])
        except CalledProcessError:
            if args["--debug"]:
                raise
            print("Failed to take screenshot. Make sure scrot is installed and /tmp/puushscrot.png is writable.", file=sys.stderr)
            return 2
        files = ["/tmp/puushscrot.png"]

    for f in files:
        try:
            url = upload_file(f, api_key)
        except:
            if args["--debug"]:
                raise
            print("Something went wrong while uploading your file.", file=sys.stderr)
            return 3

        print(url)

        if args["--clipboard"]:
            try:
                copy_to_clipboard(url)
            except:
                if args["--debug"]:
                    raise
                print("Failed to copy to clipboard. Make sure xclip is installed and /tmp/puushclip is writable.", file=sys.stderr)
                return 4

        if not args["--mute"]:
            try:
                sp.call(["play", "--no-show-progress", "--null", "--channels", "1", "synth", "0.07", "sine", "500"], stdout=sp.PIPE, stderr=sp.PIPE)
            except:
                if args["--debug"]:
                    raise
                pass

    if scrot_options is not None:
        os.remove("/tmp/puushscrot.png")


if __name__ == "__main__":
    args = docopt.docopt(__doc__, version=VERSION)
    sys.exit(main(args))

