#!/usr/bin/env python3

import os
import re
import sys
import subprocess as sp

import requests

USAGE = """puush for linux

Usage:
    puush [-c] [file]...
    puush [-c] {-2 | -3 | -4}
    puush -h

Options:
    -2      Take a screenshot of the current window and upload it
    -3      Take a screenshot of the entire desktop and upload it
    -4      Take a screenshot of a certain area and upload it
    -c      Copy the URL to clipboard additionally to STDOUT
    -m      Mute. Don't play beep.
    -h      Show this help
"""
ARGS = ["-2", "-3", "-4", "-c", "-m", "-h"]
APIURL = "https://puush.me/api/up"


def usage():
    print(USAGE)
    return 0


def upload_file(path, api_key):
    payload = {
        "k": api_key,
        "z": "something"
    }
    files = {
        "f": open(path, "rb")
    }

    r = requests.post(APIURL, data=payload, files=files)
    url = re.search("(?P<url>https?://[^\s,]+)", r.text).group("url")
    return url


def copy_to_clipboard(content):
    with open("/tmp/puushclip", "w") as f:
        f.write(content)
    sp.check_call(["xclip", "-selection", "clipboard", "-i", "/tmp/puushclip"])
    os.remove("/tmp/puushclip")


def main(args, optargs):
    if "PUUSH_API_KEY" in os.environ:
        api_key = os.environ["PUUSH_API_KEY"]
    else:
        try:
            with open(os.path.expanduser("~/.config/puush/key"), "r") as f:
                api_key = f.read().strip()
        except:
            raise
            print("Failed to get api key. Please follow the instructions at https://github.com/KoffeinFlummi/puush-linux .", file=sys.stderr)
            return 1

    files = [os.path.abspath(x) for x in args]

    scrot_options = None
    if "-2" in optargs:
        scrot_options = ["-b", "-u"]
    if "-3" in optargs:
        scrot_options = []
    if "-4" in optargs:
        scrot_options = ["-s"]

    if scrot_options is not None:
        try:
            sp.check_call(["scrot"] + scrot_options + ["/tmp/puushscrot.png"])
        except CalledProcessError:
            print("Failed to take screenshot. Make sure scrot is installed and /tmp/puushscrot.png is writable.", file=sys.stderr)
            return 2
        files = ["/tmp/puushscrot.png"]

    for f in files:
        try:
            url = upload_file(f, api_key)
        except:
            print("Something went wrong while uploading your file.", file=sys.stderr)
            return 3
        print(url)

        if "-c" in optargs:
            try:
                copy_to_clipboard(url)
            except:
                print("Failed to copy to clipboard. Make sure xclip is installed and /tmp/puushclip is writable.", file=sys.stderr)
                return 4

        if "-m" not in optargs:
            try:
                sp.call(["play", "--no-show-progress", "--null", "--channels", "1", "synth", "0.07", "sine", "500"], stdout=sp.PIPE, stderr=sp.PIPE)
            except:
                pass

    if scrot_options is not None:
        os.remove("/tmp/puushscrot.png")


if __name__ == "__main__":
    args = list(filter(lambda x: x[0] != "-", sys.argv[1:]))
    optargs = list(filter(lambda x: x[0] == "-", sys.argv[1:]))

    if "-h" in optargs or len(args) + len(optargs) == 0:
        usage()
        sys.exit(0)

    for a in optargs:
        if a not in ARGS:
            usage()
            sys.exit(1)

    sys.exit(main(args, optargs))

